name: codesolid
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8=hd037594_8
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - icu=75.1=hfee45f7_0
  - libexpat=2.7.1=hec049ff_0
  - libffi=3.5.2=he5f378a_0
  - liblzma=5.8.1=h39f12f2_2
  - liblzma-devel=5.8.1=h39f12f2_2
  - libsqlite=3.51.0=h8adb53f_0
  - libzlib=1.3.1=h8359307_2
  - ncurses=6.5=h5e97a16_3
  - openssl=3.6.0=h5503f6c_0
  - pip=25.3=pyh8b19718_0
  - python=3.12.12=h18782d2_1_cpython
  - readline=8.2=h1d1bf99_2
  - setuptools=80.9.0=pyhff2d567_0
  - tk=8.6.13=h892fb3f_2
  - wheel=0.45.1=pyhd8ed1ab_1
  - xz=5.8.1=h9a6d368_2
  - xz-gpl-tools=5.8.1=h9a6d368_2
  - xz-tools=5.8.1=h39f12f2_2
  - pip:
      - aiosqlite==0.21.0
      - alabaster==0.7.16
      - anyio==4.11.0
      - appnope==0.1.4
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.4.0
      - asttokens==3.0.0
      - async-lru==2.0.5
      - attrs==25.4.0
      - babel==2.17.0
      - beautifulsoup4==4.14.2
      - bleach==6.3.0
      - cattrs==25.3.0
      - certifi==2025.11.12
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.3.0
      - colorama==0.4.6
      - comm==0.2.3
      - contourpy==1.3.3
      - cycler==0.12.1
      - debugpy==1.8.17
      - decorator==5.2.1
      - defusedxml==0.7.1
      - docutils==0.20.1
      - esbonio==1.0.0
      - executing==2.2.1
      - fastjsonschema==2.21.2
      - fonttools==4.60.1
      - fqdn==1.5.1
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - idna==3.11
      - imagesize==1.4.1
      - importlib-metadata==8.7.0
      - ipykernel==7.1.0
      - ipython==9.7.0
      - ipython-pygments-lexers==1.1.1
      - ipywidgets==8.1.8
      - isoduration==20.11.0
      - jdesmos==0.0.4
      - jedi==0.19.2
      - jinja2==3.1.6
      - jp-proxy-widget==1.0.10
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter-cache==1.0.1
      - jupyter-client==8.6.3
      - jupyter-core==5.9.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyter-ui-poll==1.1.0
      - jupyterlab==4.4.10
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.28.0
      - jupyterlab-widgets==3.0.16
      - jupytext==1.18.1
      - kiwisolver==1.4.9
      - lark==1.3.1
      - livereload==2.7.1
      - lsprotocol==2025.0.0
      - markdown-it-py==3.0.0
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - matplotlib-inline==0.2.1
      - mdit-py-plugins==0.5.0
      - mdurl==0.1.2
      - metakernel==0.30.4
      - mistune==3.1.4
      - mpmath==1.3.0
      - myst-nb==1.3.0
      - myst-parser==4.0.1
      - narwhals==2.11.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nbsphinx==0.9.7
      - nest-asyncio==1.6.0
      - notebook-shim==0.2.4
      - numpy==2.3.4
      - octave-kernel==0.36.0
      - overrides==7.7.0
      - packaging==25.0
      - pandas==2.3.3
      - pandocfilters==1.5.1
      - parso==0.8.5
      - pexpect==4.9.0
      - pillow==12.0.0
      - platformdirs==4.5.0
      - plotly==6.4.0
      - prometheus-client==0.23.1
      - prompt-toolkit==3.0.52
      - psutil==7.1.3
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pycparser==2.23
      - pygls==2.0.0
      - pygments==2.19.2
      - pyparsing==3.2.5
      - pyspellchecker==0.8.3
      - python-dateutil==2.9.0.post0
      - python-json-logger==4.0.0
      - pytz==2025.2
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - referencing==0.37.0
      - requests==2.32.5
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - roman-numerals-py==3.1.0
      - rpds-py==0.28.0
      - scipy==1.16.3
      - seaborn==0.13.2
      - send2trash==1.8.3
      - six==1.17.0
      - sniffio==1.3.1
      - snowballstemmer==3.0.1
      - soupsieve==2.8
      - sphinx==8.2.3
      - sphinx-autobuild==2025.8.25
      - sphinx-rtd-theme==3.0.2
      - sphinxcontrib-applehelp==2.0.0
      - sphinxcontrib-devhelp==2.0.0
      - sphinxcontrib-htmlhelp==2.1.0
      - sphinxcontrib-jquery==4.1
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==2.0.0
      - sphinxcontrib-serializinghtml==2.0.0
      - sqlalchemy==2.0.44
      - stack-data==0.6.3
      - starlette==0.50.0
      - sympy==1.14.0
      - tabulate==0.9.0
      - tenacity==9.1.2
      - terminado==0.18.1
      - tinycss2==1.4.0
      - tornado==6.5.2
      - traitlets==5.14.3
      - typeguard==4.4.4
      - types-python-dateutil==2.9.0.20251108
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - uri-template==1.3.0
      - urllib3==2.5.0
      - uvicorn==0.38.0
      - watchfiles==1.1.1
      - wcwidth==0.2.14
      - webcolors==25.10.0
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - websockets==15.0.1
      - widgetsnbextension==4.0.15
      - zipp==3.23.0
prefix: /opt/homebrew/Caskroom/miniconda/base/envs/codesolid
